import { loader } from 'fumadocs-core/source';

// Minimal source for build compatibility
// In production, this would be generated by fumadocs-mdx
export const source = loader({
  baseUrl: '/docs',
  source: {
    pages: [],
    metas: [],
    files: [],
    getPage: () => undefined,
    getPages: () => [],
    getMeta: () => undefined,
    getMetas: () => [],
    pageTree: { name: 'Docs', children: [] },
    generateParams: () => [],
  } as any,
});
